# Generated by Django 3.2 on 2022-04-19 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, unique=True, verbose_name='Адрес')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Широта')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Долгота')),
                ('update_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
    ]
