# Generated by Django 3.2 on 2022-04-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_rename_amount_productitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Заказ обработан'),
            preserve_default=False,
        ),
    ]
