# Generated by Django 3.2 on 2022-04-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_order_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Стоимость'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Заказ обработан'),
        ),
    ]
