# Generated by Django 3.2 on 2022-05-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_rename_location_restaurant_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта')], db_index=True, max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
